#!usr/bin/env bash

# Alias to use lsd app to colorize the output
alias ls="exa --color-scale --icons --sort=name --sort=type --git"
alias lst="ls --tree"
alias l="ls -l --no-user"
alias lt="ls -l --tree --no-user"
alias la="ls -a"
alias lat="ls -a --tree"
alias ll="ls -la --no-user"
alias llt="ls -la --tree --no-user"

alias cd..="cd .."
alias cls="clear"

alias rm="rm -vI"
alias mv="mv -iv"
alias cp="cp -iv"

alias vi="nvim"
alias vim="nvim"

# Git aliases
alias g="git"
alias gs="git status"
alias ga="g add"
alias gaa="ga -A"
alias gc="g commit -m"
alias grs="g restore --staged"
alias gp="g push"
alias gpl="g pull"
alias gg="git log --all --decorate --oneline --graph"

alias cat="bat"
alias grep="grep --color=auto"

# Needed for the term type to be recogniced by the remote servers
alias ssh="TERM=xterm-256color ssh"
