#!usr/bin/env bash

# Alias to use lsd app to colorize the output
alias ls="exa --color-scale --icons --sort=name --sort=type"
alias lst="ls --tree"
alias l="ls -l"
alias lt="ls -l --tree"
alias la="ls -a"
alias lat="ls -a --tree"
alias ll="ls -la"
alias llt="ls -la --tree"

alias cd..="cd .."

alias vi="nvim"

# Git aliases
alias g="git"
alias gs="git status"
alias ga="g add"
alias gaa="ga -A"
alias gc="g commit -m"
alias grs="g restore --staged"
alias gp="g push"
alias gpl="g pull"

alias cat="bat"
alias grep="grep --color=auto"

alias ssh="TERM=xterm-256color ssh"
